on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  scrape-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 run.py > msg.txt
      - run: git commit -m "$(date)"
